storage:
  postgres:
    postgres_db:
      username: dagster
      password: dagster
      hostname: postgres
      db_name: dagster
      port: 5432

run_launcher:
  module: dagster.core.launcher
  class: DefaultRunLauncher

run_coordinator:
  module: dagster.core.run_coordinator
  class: QueuedRunCoordinator
